// <auto-generated />
using System;
using AppData.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppData.Migrations
{
    [DbContext(typeof(QUAN_LI_SACH_NET105Context))]
    [Migration("20230604143940_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppData.Models.Account", b =>
                {
                    b.Property<Guid>("IdnguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDNguoiDung")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaiKhoan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdnguoiDung")
                        .HasName("PK__Account__FCD7DB097A961C94");

                    b.HasIndex(new[] { "TaiKhoan" }, "UQ__Account__D5B8C7F0938C33AA")
                        .IsUnique()
                        .HasFilter("[TaiKhoan] IS NOT NULL");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("AppData.Models.GioHang", b =>
                {
                    b.Property<Guid>("Idgh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDGH")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("Idkh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDKH");

                    b.HasKey("Idgh")
                        .HasName("PK__GioHang__B87DE222D100450C");

                    b.HasIndex("Idkh");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("AppData.Models.GioHangCt", b =>
                {
                    b.Property<Guid>("Idghct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDGHCT")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("Idgh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDGH");

                    b.Property<Guid?>("Idspct")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDSPCT");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Idghct")
                        .HasName("PK__GioHangC__D592581F54369A12");

                    b.HasIndex("Idgh");

                    b.HasIndex("Idspct");

                    b.ToTable("GioHangCT", (string)null);
                });

            modelBuilder.Entity("AppData.Models.HoaDon", b =>
                {
                    b.Property<Guid>("Idhd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDHD")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("Idkh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDKH");

                    b.Property<Guid?>("Idkm")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDKM");

                    b.Property<Guid?>("Idnv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDNV");

                    b.Property<string>("MaHd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaHD");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("date");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Idhd")
                        .HasName("PK__HoaDon__B87C1A07599CB17A");

                    b.HasIndex("Idkh");

                    b.HasIndex("Idkm");

                    b.HasIndex("Idnv");

                    b.HasIndex(new[] { "MaHd" }, "UQ__HoaDon__2725A6E11AE619B6")
                        .IsUnique()
                        .HasFilter("[MaHD] IS NOT NULL");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("AppData.Models.HoaDonCt", b =>
                {
                    b.Property<Guid>("Idhdct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDHDCT")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("Idhd")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDHD");

                    b.Property<Guid?>("Idspct")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDSPCT");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Idhdct")
                        .HasName("PK__HoaDonCT__F8B33677718DB99B");

                    b.HasIndex("Idhd");

                    b.HasIndex("Idspct");

                    b.HasIndex(new[] { "SoLuong" }, "UQ__HoaDonCT__556FA067A5B4F8EF")
                        .IsUnique()
                        .HasFilter("[SoLuong] IS NOT NULL");

                    b.ToTable("HoaDonCT", (string)null);
                });

            modelBuilder.Entity("AppData.Models.KhachHang", b =>
                {
                    b.Property<Guid>("Idkh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDKH")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("IdnguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDNguoiDung");

                    b.Property<string>("Ma")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenKh")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TenKH");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Idkh")
                        .HasName("PK__KhachHan__B87DC1A74AD4F6F2");

                    b.HasIndex("IdnguoiDung");

                    b.HasIndex(new[] { "Ma" }, "UQ__KhachHan__3214CC9E87525964")
                        .IsUnique()
                        .HasFilter("[Ma] IS NOT NULL");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("AppData.Models.KhuyenMai", b =>
                {
                    b.Property<Guid>("Idkm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDKM")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("MaKm")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaKM");

                    b.Property<DateTime?>("NgayBd")
                        .HasColumnType("date")
                        .HasColumnName("NgayBD");

                    b.Property<DateTime?>("NgayKt")
                        .HasColumnType("date")
                        .HasColumnName("NgayKT");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Idkm")
                        .HasName("PK__KhuyenMa__B87DC1AAD1E6023E");

                    b.HasIndex(new[] { "MaKm" }, "UQ__KhuyenMa__2725CF1420F347DB")
                        .IsUnique()
                        .HasFilter("[MaKM] IS NOT NULL");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("AppData.Models.NhanVien", b =>
                {
                    b.Property<Guid>("Idnv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDNV")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("IdnguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDNguoiDung");

                    b.Property<string>("MaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<string>("Sdt")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNv")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TenNV");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Idnv")
                        .HasName("PK__NhanVien__B87DC9B209D9DF83");

                    b.HasIndex("IdnguoiDung");

                    b.HasIndex(new[] { "MaNv" }, "UQ__NhanVien__2725D70B6E95CB40")
                        .IsUnique()
                        .HasFilter("[MaNV] IS NOT NULL");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Nxb", b =>
                {
                    b.Property<Guid>("Idnxb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDNXB")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Mansx")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MANSX");

                    b.Property<string>("TenNxb")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TenNXB");

                    b.HasKey("Idnxb")
                        .HasName("PK__NXB__945B98FB6E74D8C6");

                    b.HasIndex(new[] { "Mansx" }, "UQ__NXB__7ABD278C2C5293DF")
                        .IsUnique()
                        .HasFilter("[MANSX] IS NOT NULL");

                    b.ToTable("NXB", (string)null);
                });

            modelBuilder.Entity("AppData.Models.SanPham", b =>
                {
                    b.Property<Guid>("Idsp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDSP")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("MaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaSP");

                    b.Property<string>("TenSp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenSP");

                    b.HasKey("Idsp")
                        .HasName("PK__SanPham__B87C02A5E1DD8D57");

                    b.HasIndex(new[] { "MaSp" }, "UQ__SanPham__2725081DD7C2DF5F")
                        .IsUnique()
                        .HasFilter("[MaSP] IS NOT NULL");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("AppData.Models.SanPhamCt", b =>
                {
                    b.Property<Guid>("Idspct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDSPCT")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("GiaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("GiaNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasDefaultValueSql("((0))");

                    b.Property<Guid?>("Idnxb")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDNXB");

                    b.Property<Guid?>("Idsp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDSP");

                    b.Property<Guid?>("Idtg")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDTG");

                    b.Property<string>("MoTa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Idspct")
                        .HasName("PK__SanPhamC__83F7208FA954EE61");

                    b.HasIndex("Idnxb");

                    b.HasIndex("Idsp");

                    b.HasIndex("Idtg");

                    b.ToTable("SanPhamCT", (string)null);
                });

            modelBuilder.Entity("AppData.Models.TacGia", b =>
                {
                    b.Property<Guid>("Idtg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDTG")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Matg")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MATG");

                    b.Property<string>("TenTg")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TenTG");

                    b.HasKey("Idtg")
                        .HasName("PK__TacGia__B87C3A8F63E83118");

                    b.HasIndex(new[] { "Matg" }, "UQ__TacGia__6023721B761EEB4A")
                        .IsUnique()
                        .HasFilter("[MATG] IS NOT NULL");

                    b.ToTable("TacGia");
                });

            modelBuilder.Entity("AppData.Models.GioHang", b =>
                {
                    b.HasOne("AppData.Models.KhachHang", "IdkhNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("Idkh")
                        .HasConstraintName("FK__GioHang__IDKH__7F2BE32F");

                    b.Navigation("IdkhNavigation");
                });

            modelBuilder.Entity("AppData.Models.GioHangCt", b =>
                {
                    b.HasOne("AppData.Models.GioHang", "IdghNavigation")
                        .WithMany("GioHangCts")
                        .HasForeignKey("Idgh")
                        .HasConstraintName("FK__GioHangCT__IDGH__7E37BEF6");

                    b.HasOne("AppData.Models.SanPhamCt", "IdspctNavigation")
                        .WithMany("GioHangCts")
                        .HasForeignKey("Idspct")
                        .HasConstraintName("FK__GioHangCT__IDSPC__7D439ABD");

                    b.Navigation("IdghNavigation");

                    b.Navigation("IdspctNavigation");
                });

            modelBuilder.Entity("AppData.Models.HoaDon", b =>
                {
                    b.HasOne("AppData.Models.KhachHang", "IdkhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("Idkh")
                        .HasConstraintName("FK__HoaDon__IDKH__797309D9");

                    b.HasOne("AppData.Models.KhuyenMai", "IdkmNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("Idkm")
                        .HasConstraintName("FK__HoaDon__IDKM__7B5B524B");

                    b.HasOne("AppData.Models.NhanVien", "IdnvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("Idnv")
                        .HasConstraintName("FK__HoaDon__IDNV__7A672E12");

                    b.Navigation("IdkhNavigation");

                    b.Navigation("IdkmNavigation");

                    b.Navigation("IdnvNavigation");
                });

            modelBuilder.Entity("AppData.Models.HoaDonCt", b =>
                {
                    b.HasOne("AppData.Models.HoaDon", "IdhdNavigation")
                        .WithMany("HoaDonCts")
                        .HasForeignKey("Idhd")
                        .HasConstraintName("FK__HoaDonCT__IDHD__76969D2E");

                    b.HasOne("AppData.Models.SanPhamCt", "IdspctNavigation")
                        .WithMany("HoaDonCts")
                        .HasForeignKey("Idspct")
                        .HasConstraintName("FK__HoaDonCT__IDSPCT__778AC167");

                    b.Navigation("IdhdNavigation");

                    b.Navigation("IdspctNavigation");
                });

            modelBuilder.Entity("AppData.Models.KhachHang", b =>
                {
                    b.HasOne("AppData.Models.Account", "IdnguoiDungNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("IdnguoiDung")
                        .HasConstraintName("FK__KhachHang__IDNgu__7C4F7684");

                    b.Navigation("IdnguoiDungNavigation");
                });

            modelBuilder.Entity("AppData.Models.NhanVien", b =>
                {
                    b.HasOne("AppData.Models.Account", "IdnguoiDungNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdnguoiDung")
                        .HasConstraintName("FK__NhanVien__IDNguo__787EE5A0");

                    b.Navigation("IdnguoiDungNavigation");
                });

            modelBuilder.Entity("AppData.Models.SanPhamCt", b =>
                {
                    b.HasOne("AppData.Models.Nxb", "IdnxbNavigation")
                        .WithMany("SanPhamCts")
                        .HasForeignKey("Idnxb")
                        .HasConstraintName("FK__SanPhamCT__IDNXB__75A278F5");

                    b.HasOne("AppData.Models.SanPham", "IdspNavigation")
                        .WithMany("SanPhamCts")
                        .HasForeignKey("Idsp")
                        .HasConstraintName("FK__SanPhamCT__IDSP__73BA3083");

                    b.HasOne("AppData.Models.TacGia", "IdtgNavigation")
                        .WithMany("SanPhamCts")
                        .HasForeignKey("Idtg")
                        .HasConstraintName("FK__SanPhamCT__IDTG__74AE54BC");

                    b.Navigation("IdnxbNavigation");

                    b.Navigation("IdspNavigation");

                    b.Navigation("IdtgNavigation");
                });

            modelBuilder.Entity("AppData.Models.Account", b =>
                {
                    b.Navigation("KhachHangs");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("AppData.Models.GioHang", b =>
                {
                    b.Navigation("GioHangCts");
                });

            modelBuilder.Entity("AppData.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonCts");
                });

            modelBuilder.Entity("AppData.Models.KhachHang", b =>
                {
                    b.Navigation("GioHangs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("AppData.Models.KhuyenMai", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("AppData.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("AppData.Models.Nxb", b =>
                {
                    b.Navigation("SanPhamCts");
                });

            modelBuilder.Entity("AppData.Models.SanPham", b =>
                {
                    b.Navigation("SanPhamCts");
                });

            modelBuilder.Entity("AppData.Models.SanPhamCt", b =>
                {
                    b.Navigation("GioHangCts");

                    b.Navigation("HoaDonCts");
                });

            modelBuilder.Entity("AppData.Models.TacGia", b =>
                {
                    b.Navigation("SanPhamCts");
                });
#pragma warning restore 612, 618
        }
    }
}
